# Generated by Django 6.0.4 on 2026-04-15 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballclub',
            name='Characteristic',
        ),
        migrations.AlterField(
            model_name='footballclub',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='api.country'),
        ),
        migrations.AlterField(
            model_name='footballclub',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='api.league'),
        ),
        migrations.AddField(
            model_name='footballclub',
            name='characteristic',
            field=models.ManyToManyField(blank=True, related_name='clubs', to='api.characteristic'),
        ),
    ]
